// Sidebar
export const SIDEBAR_VISIBILITY_TOGGLE = "SIDEBAR_VISIBILITY_TOGGLE";
export const SIDEBAR_VISIBILITY_SHOW = "SIDEBAR_VISIBILITY_SHOW";
export const SIDEBAR_VISIBILITY_HIDE = "SIDEBAR_VISIBILITY_HIDE";
export const SIDEBAR_STICKY_TOGGLE = "SIDEBAR_STICKY_TOGGLE";
export const SIDEBAR_STICKY_ENABLE = "SIDEBAR_STICKY_ENABLE";
export const SIDEBAR_STICKY_DISABLE = "SIDEBAR_STICKY_DISABLE";

// Layout
export const LAYOUT_BOXED_TOGGLE = "LAYOUT_BOXED_TOGGLE";
export const LAYOUT_BOXED_ENABLE = "LAYOUT_BOXED_ENABLE";
export const LAYOUT_BOXED_DISABLE = "LAYOUT_BOXED_DISABLE";

// Theme
export const THEME_TOGGLE = "THEME_TOGGLE";

//Auth

export const REGISTER_REQUEST = "USERS_REGISTER_REQUEST";
export const REGISTER_SUCCESS = "USERS_REGISTER_SUCCESS";
export const REGISTER_FAILURE = "USERS_REGISTER_FAILURE";

export const LOGIN_REQUEST = "USERS_LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USERS_LOGIN_FAILURE";

export const LOGOUT = "USERS_LOGOUT";

export const FORGOT_PASSWORD_REQUEST = "USERS_FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "USERS_FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "USERS_FORGOT_PASSWORD_FAILURE";

export const RESET_PASSWORD_REQUEST = "USERS_RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "USERS_RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "USERS_RESET_PASSWORD_FAILURE";

//Alert
export const SUCCESS = "ALERT_SUCCESS";
export const ERROR = "ALERT_ERROR";
export const CLEAR = "ALERT_CLEAR";

//user

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const GET_USER_BY_ID_REQUEST = "GET_USER_BY_ID_REQUEST";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAILURE = "GET_USER_BY_ID_FAILURE";

export const GET_USER_ORDERS_REQUEST = "GET_USER_ORDERS_REQUEST";
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS";
export const GET_USER_ORDERS_FAILURE = "GET_USER_ORDERS_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const INVITE_USER_REQUEST = "INVITE_USER_REQUEST";
export const INVITE_USER_SUCCESS = "INVITE_USER_SUCCESS";
export const INVITE_USER_FAILURE = "INVITE_USER_FAILURE";

//contact

export const GET_CONTACTS_REQUEST = "GET_CONTACTS_REQUEST";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAILURE = "GET_CONTACTS_FAILURE";

export const GET_CUSTOMER_CONTACTS_REQUEST = "GET_CUSTOMER_CONTACTS_REQUEST";
export const GET_CUSTOMER_CONTACTS_SUCCESS = "GET_CUSTOMER_CONTACTS_SUCCESS";
export const GET_CUSTOMER_CONTACTS_FAILURE = "GET_CUSTOMER_CONTACTS_FAILURE";

export const GET_VENDOR_CONTACTS_REQUEST = "GET_VENDOR_CONTACTS_REQUEST";
export const GET_VENDOR_CONTACTS_SUCCESS = "GET_VENDOR_CONTACTS_SUCCESS";
export const GET_VENDOR_CONTACTS_FAILURE = "GET_VENDOR_CONTACTS_FAILURE";

export const GET_VENDOR_CONTACTS_WITH_FILTERS_REQUEST =
  "GET_VENDOR_CONTACTS_WITH_FILTERS_REQUEST";
export const GET_VENDOR_CONTACTS_WITH_FILTERS_SUCCESS =
  "GET_VENDOR_CONTACTS_WITH_FILTERS_SUCCESS";
export const GET_VENDOR_CONTACTS_WITH_FILTERS_FAILURE =
  "GET_VENDOR_CONTACTS_WITH_FILTERS_FAILURE";

export const GET_CUSTOMER_CONTACTS_WITH_FILTERS_REQUEST =
  "GET_CUSTOMER_CONTACTS_WITH_FILTERS_REQUEST";
export const GET_CUSTOMER_CONTACTS_WITH_FILTERS_SUCCESS =
  "GET_CUSTOMER_CONTACTS_WITH_FILTERS_SUCCESS";
export const GET_CUSTOMER_CONTACTS_WITH_FILTERS_FAILURE =
  "GET_CUSTOMER_CONTACTS_WITH_FILTERS_FAILURE";

export const CREATE_NEW_CONTACT_REQUEST = "CREATE_NEW_CONTACT_REQUEST";
export const CREATE_NEW_CONTACT_SUCCESS = "CREATE_NEW_CONTACT_SUCCESS";
export const CREATE_NEW_CONTACT_FAILURE = "CREATE_NEW_CONTACT_FAILURE";

export const UPDATE_CONTACT_REQUEST = "UPDATE_CONTACT_REQUEST";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_FAILURE = "UPDATE_CONTACT_FAILURE";

//lookup

export const GET_COUNTRIES_LOOKUP_REQUEST = "GET_COUNTRIES_LOOKUP_REQUEST";
export const GET_COUNTRIES_LOOKUP_SUCCESS = "GET_COUNTRIES_LOOKUP_SUCCESS";
export const GET_COUNTRIES_LOOKUP_FAILURE = "GET_COUNTRIES_LOOKUP_FAILURE";

export const GET_UNITS_LOOKUP_REQUEST = "GET_UNITS_LOOKUP_REQUEST";
export const GET_UNITS_LOOKUP_SUCCESS = "GET_UNITS_LOOKUP_SUCCESS";
export const GET_UNITS_LOOKUP_FAILURE = "GET_UNITS_LOOKUP_FAILURE";

export const GET_INDUSTRIES_LOOKUP_REQUEST = "GET_INDUSTRIES_LOOKUP_REQUEST";
export const GET_INDUSTRIES_LOOKUP_SUCCESS = "GET_INDUSTRIES_LOOKUP_SUCCESS";
export const GET_INDUSTRIES_LOOKUP_FAILURE = "GET_INDUSTRIES_LOOKUP_FAILURE";

export const GET_VARIANTS_LOOKUP_REQUEST = "GET_VARIANTS_LOOKUP_REQUEST";
export const GET_VARIANTS_LOOKUP_SUCCESS = "GET_VARIANTS_LOOKUP_SUCCESS";
export const GET_VARIANTS_LOOKUP_FAILURE = "GET_VARIANTS_LOOKUP_FAILURE";

export const GET_CONTACTS_LOOKUP_REQUEST = "GET_CONTACTS_LOOKUP_REQUEST";
export const GET_CONTACTS_LOOKUP_SUCCESS = "GET_CONTACTS_LOOKUP_SUCCESS";
export const GET_CONTACTS_LOOKUP_FAILURE = "GET_CONTACTS_LOOKUP_FAILURE";

export const GET_DATE_FORMATS_LOOKUP_REQUEST =
  "GET_DATE_FORMATS_LOOKUP_REQUEST";
export const GET_DATE_FORMATS_LOOKUP_SUCCESS =
  "GET_DATE_FORMATS_LOOKUP_SUCCESS";
export const GET_DATE_FORMATS_LOOKUP_FAILURE =
  "GET_DATE_FORMATS_LOOKUP_FAILURE";

export const GET_FISCAL_YEARS_LOOKUP_REQUEST =
  "GET_FISCAL_YEARS_LOOKUP_REQUEST";
export const GET_FISCAL_YEARS_LOOKUP_SUCCESS =
  "GET_FISCAL_YEARS_LOOKUP_SUCCESS";
export const GET_FISCAL_YEARS_LOOKUP_FAILURE =
  "GET_FISCAL_YEARS_LOOKUP_FAILURE";

export const GET_LANGUAGES_LOOKUP_REQUEST = "GET_LANGUAGES_LOOKUP_REQUEST";
export const GET_LANGUAGES_LOOKUP_SUCCESS = "GET_LANGUAGES_LOOKUP_SUCCESS";
export const GET_LANGUAGES_LOOKUP_FAILURE = "GET_LANGUAGES_LOOKUP_FAILURE";

export const GET_TIME_ZONES_LOOKUP_REQUEST = "GET_TIME_ZONES_LOOKUP_REQUEST";
export const GET_TIME_ZONES_LOOKUP_SUCCESS = "GET_TIME_ZONES_LOOKUP_SUCCESS";
export const GET_TIME_ZONES_LOOKUP_FAILURE = "GET_TIME_ZONES_LOOKUP_FAILURE";

export const GET_SALES_ORDER_CHANNELS_LOOKUP_REQUEST =
  "GET_SALES_ORDER_CHANNELS_LOOKUP_REQUEST";
export const GET_SALES_ORDER_CHANNELS_LOOKUP_SUCCESS =
  "GET_SALES_ORDER_CHANNELS_LOOKUP_SUCCESS";
export const GET_SALES_ORDER_CHANNELS_LOOKUP_FAILURE =
  "GET_SALES_ORDER_CHANNELS_LOOKUP_FAILURE";

export const GET_INVENTORY_UPDATE_TYPES_LOOKUP_REQUEST =
  "GET_INVENTORY_UPDATE_TYPES_LOOKUP_REQUEST";
export const GET_INVENTORY_UPDATE_TYPES_LOOKUP_SUCCESS =
  "GET_INVENTORY_UPDATE_TYPES_LOOKUP_SUCCESS";
export const GET_INVENTORY_UPDATE_TYPES_LOOKUP_FAILURE =
  "GET_INVENTORY_UPDATE_TYPES_LOOKUP_FAILURE";

//organization

export const GET_ORGANIZATION_REQUEST = "GET_ORGANIZATION_REQUEST";
export const GET_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const GET_ORGANIZATION_FAILURE = "GET_ORGANIZATION_FAILURE";

export const GET_ORGANIZATION_LOCATIONS_REQUEST =
  "GET_ORGANIZATION_LOCATIONS_REQUEST";
export const GET_ORGANIZATION_LOCATIONS_SUCCESS =
  "GET_ORGANIZATION_LOCATIONS_SUCCESS";
export const GET_ORGANIZATION_LOCATIONS_FAILURE =
  "GET_ORGANIZATION_LOCATIONS_FAILURE";

export const GET_ALL_ORGANIZATION_LOCATIONS_REQUEST =
  "GET_ALL_ORGANIZATION_LOCATIONS_REQUEST";
export const GET_ALL_ORGANIZATION_LOCATIONS_SUCCESS =
  "GET_ALL_ORGANIZATION_LOCATIONS_SUCCESS";
export const GET_ALL_ORGANIZATION_LOCATIONS_FAILURE =
  "GET_ALL_ORGANIZATION_LOCATIONS_FAILURE";

export const GET_ORGANIZATION_TAXES_REQUEST = "GET_ORGANIZATION_TAXES_REQUEST";
export const GET_ORGANIZATION_TAXES_SUCCESS = "GET_ORGANIZATION_TAXES_SUCCESS";
export const GET_ORGANIZATION_TAXES_FAILURE = "GET_ORGANIZATION_TAXES_FAILURE";

export const GET_ORGANIZATION_NOTIFICATIONS_REQUEST =
  "GET_ORGANIZATION_NOTIFICATIONS_REQUEST";
export const GET_ORGANIZATION_NOTIFICATIONS_SUCCESS =
  "GET_ORGANIZATION_NOTIFICATIONS_SUCCESS";
export const GET_ORGANIZATION_NOTIFICATIONS_FAILURE =
  "GET_ORGANIZATION_NOTIFICATIONS_FAILURE";

export const CREATE_ORGANIZATION_TAXES_REQUEST =
  "CREATE_ORGANIZATION_TAXES_REQUEST";
export const CREATE_ORGANIZATION_TAXES_SUCCESS =
  "CREATE_ORGANIZATION_TAXES_SUCCESS";
export const CREATE_ORGANIZATION_TAXES_FAILURE =
  "CREATE_ORGANIZATION_TAXES_FAILURE";

export const CREATE_ORGANIZATION_LOCATIONS_REQUEST =
  "CREATE_ORGANIZATION_LOCATIONS_REQUEST";
export const CREATE_ORGANIZATION_LOCATIONS_SUCCESS =
  "CREATE_ORGANIZATION_LOCATIONS_SUCCESS";
export const CREATE_ORGANIZATION_LOCATIONS_FAILURE =
  "CREATE_ORGANIZATION_LOCATIONS_FAILURE";

export const UPDATE_ORGANIZATION_REQUEST = "UPDATE_ORGANIZATION_REQUEST";
export const UPDATE_ORGANIZATION_SUCCESS = "UPDATE_ORGANIZATION_SUCCESS";
export const UPDATE_ORGANIZATION_FAILURE = "UPDATE_ORGANIZATION_FAILURE";

export const UPDATE_ORGANIZATION_LOCATION_REQUEST =
  "UPDATE_ORGANIZATION_LOCATION_REQUEST";
export const UPDATE_ORGANIZATION_LOCATION_SUCCESS =
  "UPDATE_ORGANIZATION_LOCATION_SUCCESS";
export const UPDATE_ORGANIZATION_LOCATION_FAILURE =
  "UPDATE_ORGANIZATION_LOCATION_FAILURE";

export const UPDATE_ORGANIZATION_TAX_REQUEST =
  "UPDATE_ORGANIZATION_TAX_REQUEST";
export const UPDATE_ORGANIZATION_TAX_SUCCESS =
  "UPDATE_ORGANIZATION_TAX_SUCCESS";
export const UPDATE_ORGANIZATION_TAX_FAILURE =
  "UPDATE_ORGANIZATION_TAX_FAILURE";

export const UPDATE_ORGANIZATION_NOTIFICATIONS_REQUEST =
  "UPDATE_ORGANIZATION_NOTIFICATIONS_REQUEST";
export const UPDATE_ORGANIZATION_NOTIFICATIONS_SUCCESS =
  "UPDATE_ORGANIZATION_NOTIFICATIONS_SUCCESS";
export const UPDATE_ORGANIZATION_NOTIFICATIONS_FAILURE =
  "UPDATE_ORGANIZATION_NOTIFICATIONS_FAILURE";

//organization_users

export const GET_ORGANIZATION_USERS_REQUEST = "GET_ORGANIZATION_USERS_REQUEST";
export const GET_ORGANIZATION_USERS_SUCCESS = "GET_ORGANIZATION_USERS_SUCCESS";
export const GET_ORGANIZATION_USERS_FAILURE = "GET_ORGANIZATION_USERS_FAILURE";

export const GET_ALL_ORGANIZATION_USERS_REQUEST =
  "GET_ALL_ORGANIZATION_USERS_REQUEST";
export const GET_ALL_ORGANIZATION_USERS_SUCCESS =
  "GET_ALL_ORGANIZATION_USERS_SUCCESS";
export const GET_ALL_ORGANIZATION_USERS_FAILURE =
  "GET_ALL_ORGANIZATION_USERS_FAILURE";

export const INVITE_ORGANIZATION_USERS_REQUEST =
  "INVITE_ORGANIZATION_USERS_REQUEST";
export const INVITE_ORGANIZATION_USERS_SUCCESS =
  "INVITE_ORGANIZATION_USERS_SUCCESS";
export const INVITE_ORGANIZATION_USERS_FAILURE =
  "INVITE_ORGANIZATION_USERS_FAILURE";

export const DELETE_ORGANIZATION_USERS_REQUEST =
  "DELETE_ORGANIZATION_USERS_REQUEST";
export const DELETE_ORGANIZATION_USERS_SUCCESS =
  "DELETE_ORGANIZATION_USERS_SUCCESS";
export const DELETE_ORGANIZATION_USERS_FAILURE =
  "DELETE_ORGANIZATION_USERS_FAILURE";

export const UPDATE_ORGANIZATION_USERS_REQUEST =
  "UPDATE_ORGANIZATION_USERS_REQUEST";
export const UPDATE_ORGANIZATION_USERS_SUCCESS =
  "UPDATE_ORGANIZATION_USERS_SUCCESS";
export const UPDATE_ORGANIZATION_USERS_FAILURE =
  "UPDATE_ORGANIZATION_USERS_FAILURE";

//permissions

export const GET_PERMISSIONS_REQUEST = "GET_PERMISSIONS_REQUEST";
export const GET_PERMISSIONS_SUCCESS = "GET_PERMISSIONS_SUCCESS";
export const GET_PERMISSIONS_FAILURE = "GET_PERMISSIONS_FAILURE";

//roles

export const GET_ROLES_REQUEST = "GET_ROLES_REQUEST";
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_ROLES_FAILURE = "GET_ROLES_FAILURE";

export const GET_ROLE_REQUEST = "GET_ROLE_REQUEST";
export const GET_ROLE_SUCCESS = "GET_ROLE_SUCCESS";
export const GET_ROLE_FAILURE = "GET_ROLE_FAILURE";

export const GET_ROLE_PERMISSIONS_REQUEST = "GET_ROLE_PERMISSIONS_REQUEST";
export const GET_ROLE_PERMISSIONS_SUCCESS = "GET_ROLE_PERMISSIONS_SUCCESS";
export const GET_ROLE_PERMISSIONS_FAILURE = "GET_ROLE_PERMISSIONS_FAILURE";

export const CREATE_ROLES_REQUEST = "CREATE_ROLES_REQUEST";
export const CREATE_ROLES_SUCCESS = "CREATE_ROLES_SUCCESS";
export const CREATE_ROLES_FAILURE = "CREATE_ROLES_FAILURE";

export const UPDATE_ROLES_REQUEST = "UPDATE_ROLES_REQUEST";
export const UPDATE_ROLES_SUCCESS = "UPDATE_ROLES_SUCCESS";
export const UPDATE_ROLES_FAILURE = "UPDATE_ROLES_FAILURE";

//item

export const CREATE_NEW_ITEM_REQUEST = "CREATE_NEW_ITEM_REQUEST";
export const CREATE_NEW_ITEM_SUCCESS = "CREATE_NEW_ITEM_SUCCESS";
export const CREATE_NEW_ITEM_FAILURE = "CREATE_NEW_ITEM_FAILURE";

export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_FAILURE = "UPDATE_ITEM_FAILURE";

export const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAILURE = "DELETE_ITEM_FAILURE";

export const GET_ALL_ITEMS_REQUEST = "GET_ALL_ITEMS_REQUEST";
export const GET_ALL_ITEMS_SUCCESS = "GET_ALL_ITEMS_SUCCESS";
export const GET_ALL_ITEMS_FAILURE = "GET_ALL_ITEMS_FAILURE";

export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE";

export const GET_ITEM_REQUEST = "GET_ITEM_REQUEST";
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";
export const GET_ITEM_FAILURE = "GET_ITEM_FAILURE";

export const GET_ITEM_DETAILS_REQUEST = "GET_ITEM_DETAILS_REQUEST";
export const GET_ITEM_DETAILS_SUCCESS = "GET_ITEM_DETAILS_SUCCESS";
export const GET_ITEM_DETAILS_FAILURE = "GET_ITEM_DETAILS_FAILURE";

export const GET_ITEM_OPTIONS_REQUEST = "GET_ITEM_OPTIONS_REQUEST";
export const GET_ITEM_OPTIONS_SUCCESS = "GET_ITEM_OPTIONS_SUCCESS";
export const GET_ITEM_OPTIONS_FAILURE = "GET_ITEM_OPTIONS_FAILURE";

export const GET_ITEM_VALUES_REQUEST = "GET_ITEM_VALUES_REQUEST";
export const GET_ITEM_VALUES_SUCCESS = "GET_ITEM_VALUES_SUCCESS";
export const GET_ITEM_VALUES_FAILURE = "GET_ITEM_VALUES_FAILURE";

export const CREATE_ITEM_OPTION_REQUEST = "CREATE_ITEM_OPTION_REQUEST";
export const CREATE_ITEM_OPTION_SUCCESS = "CREATE_ITEM_OPTION_SUCCESS";
export const CREATE_ITEM_OPTION_FAILURE = "CREATE_ITEM_OPTION_FAILURE";

export const CREATE_ITEM_VARIANT_VALUES_REQUEST =
  "CREATE_ITEM_VARIANT_VALUES_REQUEST";
export const CREATE_ITEM_VARIANT_VALUES_SUCCESS =
  "CREATE_ITEM_VARIANT_VALUES_SUCCESS";
export const CREATE_ITEM_VARIANT_VALUES_FAILURE =
  "CREATE_ITEM_VARIANT_VALUES_FAILURE";

//manufacturer

export const CREATE_NEW_MANUFACTURER_REQUEST =
  "CREATE_NEW_MANUFACTURER_REQUEST";
export const CREATE_NEW_MANUFACTURER_SUCCESS =
  "CREATE_NEW_MANUFACTURER_SUCCESS";
export const CREATE_NEW_MANUFACTURER_FAILURE =
  "CREATE_NEW_MANUFACTURER_FAILURE";

export const GET_MANUFACTURERS_REQUEST = "GET_MANUFACTURERS_REQUEST";
export const GET_MANUFACTURERS_SUCCESS = "GET_MANUFACTURERS_SUCCESS";
export const GET_MANUFACTURERS_FAILURE = "GET_MANUFACTURERS_FAILURE";

//brand

export const GET_BRANDS_REQUEST = "GET_BRANDS_REQUEST";
export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS";
export const GET_BRANDS_FAILURE = "GET_BRANDS_FAILURE";

export const CREATE_NEW_BRAND_REQUEST = "CREATE_NEW_BRAND_REQUEST";
export const CREATE_NEW_BRAND_SUCCESS = "CREATE_NEW_BRAND_SUCCESS";
export const CREATE_NEW_BRAND_FAILURE = "CREATE_NEW_BRAND_FAILURE";

//category

export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const CREATE_NEW_CATEGORY_REQUEST = "CREATE_NEW_CATEGORY_REQUEST";
export const CREATE_NEW_CATEGORY_SUCCESS = "CREATE_NEW_CATEGORY_SUCCESS";
export const CREATE_NEW_CATEGORY_FAILURE = "CREATE_NEW_CATEGORY_FAILURE";

//validate settings

export const VALIDATE_SETTINGS_REQUEST = "VALIDATE_SETTINGS_REQUEST";
export const VALIDATE_SETTINGS_SUCCESS = "VALIDATE_SETTINGS_SUCCESS";
export const VALIDATE_SETTINGS_FAILURE = "VALIDATE_SETTINGS_FAILURE";

//inventoires

export const GET_INVENTORIES_WITH_FILTERS_REQUEST =
  "GET_INVENTORIES_WITH_FILTERS_REQUEST";
export const GET_INVENTORIES_WITH_FILTERS_SUCCESS =
  "GET_INVENTORIES_WITH_FILTERS_SUCCESS";
export const GET_INVENTORIES_WITH_FILTERS_FAILURE =
  "GET_INVENTORIES_WITH_FILTERS_FAILURE";

export const GET_INVENTORIES_REQUEST = "GET_INVENTORIES_REQUEST";
export const GET_INVENTORIES_SUCCESS = "GET_INVENTORIES_SUCCESS";
export const GET_INVENTORIES_FAILURE = "GET_INVENTORIES_FAILURE";

//sales order

export const GET_SALES_ORDER_COUNT_REQUEST = "GET_SALES_ORDER_COUNT_REQUEST";
export const GET_SALES_ORDER_COUNT_SUCCESS = "GET_SALES_ORDER_COUNT_SUCCESS";
export const GET_SALES_ORDER_COUNT_FAILURE = "GET_SALES_ORDER_COUNT_FAILURE";

export const GET_SALES_ORDER_REQUEST = "GET_SALES_ORDER_REQUEST";
export const GET_SALES_ORDER_SUCCESS = "GET_SALES_ORDER_SUCCESS";
export const GET_SALES_ORDER_FAILURE = "GET_SALES_ORDER_FAILURE";

export const CREATE_SALES_ORDER_REQUEST = "CREATE_SALES_ORDER_REQUEST";
export const CREATE_SALES_ORDER_SUCCESS = "CREATE_SALES_ORDER_SUCCESS";
export const CREATE_SALES_ORDER_FAILURE = "CREATE_SALES_ORDER_FAILURE";

export const UPDATE_SALES_ORDER_REQUEST = "UPDATE_SALES_ORDER_REQUEST";
export const UPDATE_SALES_ORDER_SUCCESS = "UPDATE_SALES_ORDER_SUCCESS";
export const UPDATE_SALES_ORDER_FAILURE = "UPDATE_SALES_ORDER_FAILURE";

export const GET_SALES_ORDERS_WITH_FILTERS_REQUEST =
  "GET_SALES_ORDERS_WITH_FILTERS_REQUEST";
export const GET_SALES_ORDERS_WITH_FILTERS_SUCCESS =
  "GET_SALES_ORDERS_WITH_FILTERS_SUCCESS";
export const GET_SALES_ORDERS_WITH_FILTERS_FAILURE =
  "GET_SALES_ORDERS_WITH_FILTERS_FAILURE";

export const GET_SALES_ORDERS_REQUEST = "GET_SALES_ORDERS_REQUEST";
export const GET_SALES_ORDERS_SUCCESS = "GET_SALES_ORDERS_SUCCESS";
export const GET_SALES_ORDERS_FAILURE = "GET_SALES_ORDERS_FAILURE";

//inventoryAdjustments

export const GET_INVENTORY_ADJUSTMENTS_WITH_FILTERS_REQUEST =
  "GET_INVENTORY_ADJUSTMENTS_WITH_FILTERS_REQUEST";
export const GET_INVENTORY_ADJUSTMENTS_WITH_FILTERS_SUCCESS =
  "GET_INVENTORY_ADJUSTMENTS_WITH_FILTERS_SUCCESS";
export const GET_INVENTORY_ADJUSTMENTS_WITH_FILTERS_FAILURE =
  "GET_INVENTORY_ADJUSTMENTS_WITH_FILTERS_FAILURE";

export const GET_INVENTORY_ADJUSTMENTS_REQUEST =
  "GET_INVENTORY_ADJUSTMENTS_REQUEST";
export const GET_INVENTORY_ADJUSTMENTS_SUCCESS =
  "GET_INVENTORY_ADJUSTMENTS_SUCCESS";
export const GET_INVENTORY_ADJUSTMENTS_FAILURE =
  "GET_INVENTORY_ADJUSTMENTS_FAILURE";

export const GET_INVENTORY_ADJUSTMENT_REQUEST =
  "GET_INVENTORY_ADJUSTMENT_REQUEST";
export const GET_INVENTORY_ADJUSTMENT_SUCCESS =
  "GET_INVENTORY_ADJUSTMENT_SUCCESS";
export const GET_INVENTORY_ADJUSTMENT_FAILURE =
  "GET_INVENTORY_ADJUSTMENT_FAILURE";

export const GET_INVENTORY_ADJUSTMENT_REASONS_REQUEST =
  "GET_INVENTORY_ADJUSTMENT_REASONS_REQUEST";
export const GET_INVENTORY_ADJUSTMENT_REASONS_SUCCESS =
  "GET_INVENTORY_ADJUSTMENT_REASONS_SUCCESS";
export const GET_INVENTORY_ADJUSTMENT_REASONS_FAILURE =
  "GET_INVENTORY_ADJUSTMENT_REASONS_FAILURE";

export const CREATE_INVENTORY_ADJUSTMENT_REQUEST =
  "CREATE_INVENTORY_ADJUSTMENT_REQUEST";
export const CREATE_INVENTORY_ADJUSTMENT_SUCCESS =
  "CREATE_INVENTORY_ADJUSTMENT_SUCCESS";
export const CREATE_INVENTORY_ADJUSTMENT_FAILURE =
  "CREATE_INVENTORY_ADJUSTMENT_FAILURE";

export const UPDATE_INVENTORY_ADJUSTMENT_REQUEST =
  "UPDATE_INVENTORY_ADJUSTMENT_REQUEST";
export const UPDATE_INVENTORY_ADJUSTMENT_SUCCESS =
  "UPDATE_INVENTORY_ADJUSTMENT_SUCCESS";
export const UPDATE_INVENTORY_ADJUSTMENT_FAILURE =
  "UPDATE_INVENTORY_ADJUSTMENT_FAILURE";

//sales channel

export const CREATE_SALES_CHANNEL_REQUEST = "CREATE_SALES_CHANNEL_REQUEST";
export const CREATE_SALES_CHANNEL_SUCCESS = "CREATE_SALES_CHANNEL_SUCCESS";
export const CREATE_SALES_CHANNEL_FAILURE = "CREATE_SALES_CHANNEL_FAILURE";

export const UPDATE_SALES_CHANNEL_REQUEST = "UPDATE_SALES_CHANNEL_REQUEST";
export const UPDATE_SALES_CHANNEL_SUCCESS = "UPDATE_SALES_CHANNEL_SUCCESS";
export const UPDATE_SALES_CHANNEL_FAILURE = "UPDATE_SALES_CHANNEL_FAILURE";

export const GET_SALES_CHANNELS_REQUEST = "GET_SALES_CHANNELS_REQUEST";
export const GET_SALES_CHANNELS_SUCCESS = "GET_SALES_CHANNELS_SUCCESS";
export const GET_SALES_CHANNELS_FAILURE = "GET_SALES_CHANNELS_FAILURE";

export const GET_DIRECT_CHANNEL_LOCATIONS_REQUEST =
  "GET_DIRECT_CHANNEL_LOCATIONS_REQUEST";
export const GET_DIRECT_CHANNEL_LOCATIONS_SUCCESS =
  "GET_DIRECT_CHANNEL_LOCATIONS_SUCCESS";
export const GET_DIRECT_CHANNEL_LOCATIONS_FAILURE =
  "GET_DIRECT_CHANNEL_LOCATIONS_FAILURE";

export const GET_SALES_CHANNEL_BY_ID_REQUEST =
  "GET_SALES_CHANNEL_BY_ID_REQUEST";
export const GET_SALES_CHANNEL_BY_ID_SUCCESS =
  "GET_SALES_CHANNEL_BY_ID_SUCCESS";
export const GET_SALES_CHANNEL_BY_ID_FAILURE =
  "GET_SALES_CHANNEL_BY_ID_FAILURE";
